### ISSUE TITLE
[FFA/32] Jungle Arena

### ISSUE THREAD

**Issue by arcadeboss** [OvercastCommunity/PublicMaps#33]
### Checklist

- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map.
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the [README](https://github.com/OvercastCommunity/CommunityMaps#readme).
- [X] I have read and understood the  [map submission guidelines](https://oc.tc/submissions).
- [X] I have created an XML file.
- [X] I have created a map image.
- [X] I have uploaded the map zip file to a file sharing service.
- [X] The map has been tested locally to make sure it works.

### Map Name

Jungle Arena

### Gamemode & Map Description

Through a partnership between JIGABOT and arcadeboss, an ancient OG minecraft PVP map is being brought back for players enjoyment.  In the "old long since" this map once ran 24/7, and some players spent the whole day there.

This map is suitable for almost any number of players from 2 to 100, currently targeted to 32.

The map is a PVP arena complex, with several areas, secret passages and a couple of traps.

The XML is setup as a FFA, mimicking the original gameplay, with a similar kit.   Players spawn in a lobby, and upon exiting the lobby, a PVP kit is provided for a battle of 10 minutes.

### Team Sizes

no teams, free-for-all, 32 slots

### Screenshots

https://imgur.com/a/e7PHY9h

### XML

https://gist.github.com/arcadeboss/e58393e2541a01b40526b77755ed7f38

### Map Image

![map](https://github.com/OvercastCommunity/CommunityMaps/assets/3164203/4c182e5c-d1ee-494d-99b7-643bc0a4a2de)

### Map Download

**Comment by TheRealPear** [comment]
Loaded onto PrivateMaps repository.
