### ISSUE TITLE
[Cake Day] iron respawns inside defense

### ISSUE THREAD

**Issue by RuedigerLP** [OvercastCommunity/PublicMaps#6]
Cake Day
When a defense get more established the respawning iron is an obstacle to furthering the digging efforts.

I'd suggest removing respawning iron from the current location and maybe adding a respawning iron supply to the cake infront of spawn.

**Comment by calcastor** [comment]
closed by 7903d3ff8cb79c8a66cf0c44cf5ab476eb773ddf
